'use strict';
(()=>{
const $=id=>document.getElementById(id),n=(tag,text,cls)=>{const x=document.createElement(tag);x.textContent=text??'';if(cls)x.className=cls;return x},price=v=>typeof v==='number'?v.toFixed(2):'—';
let data=null,reports=null;
const date=(v,tz='Asia/Shanghai')=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const views=['tonight','pre','mobserve','cl20','structure','post'];
function navigate(){const id=views.includes(location.hash.slice(1))?location.hash.slice(1):'tonight';for(const v of views)$(v).hidden=v!==id;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===id)));$('workbenchSidebar').classList.remove('is-open');document.querySelector('.mobile-nav-toggle').setAttribute('aria-expanded','false')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.view});window.addEventListener('hashchange',navigate);navigate();
const toggle=document.querySelector('.mobile-nav-toggle');toggle.onclick=()=>toggle.setAttribute('aria-expanded',String($('workbenchSidebar').classList.toggle('is-open')));document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('workbenchSidebar').classList.remove('is-open');toggle.setAttribute('aria-expanded','false')}});
function empty(body,cols){const tr=n('tr'),td=n('td','暂无记录');td.colSpan=cols;tr.append(td);body.append(tr)}
function stock(r){const td=n('td');td.append(n('b',r.name),n('small',r.code));if(r.in_futu)td.append(n('small','富途名单','feed-category'));return td}
function mrows(){const q=$('m-search').value.trim().toLowerCase(),scope=$('m-scope').value,body=$('m-rows');body.replaceChildren();for(const r of data.m.rows.filter(r=>(!scope||r.in_futu)&&(r.code+r.name).toLowerCase().includes(q))){const tr=n('tr');tr.append(stock(r),n('td',r.category,'feed-category'),n('td',r.key_date),n('td',r.volume_ratio?price(r.volume_ratio)+'×':'—'),n('td',r.stage));body.append(tr)}if(!body.children.length)empty(body,5)}
function clrows(){const q=$('cl-search').value.trim().toLowerCase(),kind=$('cl-kind').value,body=$('cl-rows');body.replaceChildren();for(const r of data.cl20.rows.filter(r=>(!kind||r.kind===kind)&&(r.code+r.name).toLowerCase().includes(q))){const tr=n('tr'),td=n('td'),revoked=/撤销|修订/.test(r.kind);td.append(n('b',r.label,revoked?'signal-muted':r.label?.includes('B')?'signal-buy':'signal-sell'));if(revoked)td.append(n('small',r.replacement?'改为 '+r.replacement:'原信号已移除'));tr.append(n('td',date(r.detected_at)),stock(r),td,n('td',r.kind,revoked?'signal-muted':'feed-category'),n('td',price(r.price)),n('td',r.pivot_time));body.append(tr)}if(!body.children.length)empty(body,6)}
function render(){const t=data.tonight;$('tonight-meta').textContent=`${date(t.generated_at_bj)} 北京 · 日线 ${t.daily_as_of}`;$('market-gate').textContent=t.market_gate_closed?'市场门关闭 · 只观察':'市场门打开 · 等待个股确认';$('market-gate').className='gate '+(t.market_gate_closed?'wait':'confirm');const box=$('tonight-content');box.replaceChildren();for(const r of t.candidates){const a=n('article',null,'trade-plan');const h=n('div',null,'plan-heading');h.append(n('h3',r.code.replace('US.','')+' · '+r.name),n('span',r.action,'tag'));a.append(h,n('p',`${r.quote_session} ${price(r.quote)} USD`,'quote'));const dl=n('dl',null,'price-grid');for(const [label,key] of [['第一观察','first_observation'],['买入确认','buy_confirmation'],['最高接受','maximum_acceptable'],['失效价','invalidation'],['第一减仓','first_reduce'],['最终目标','final_target']]){const d=n('div');d.append(n('dt',label),n('dd',price(r[key]),key==='invalidation'?'em-risk':'em-key'));dl.append(d)}a.append(dl,n('p',r.intraday_confirmation,'plan-condition'));box.append(a)}if(!t.candidates.length)box.append(n('p','暂无符合条件的候选'));
$('m-meta').textContent=`${data.m.date} 完整RTH日线 · ${data.m.rows.length}只候选 · 富途${data.m.rows.filter(r=>r.in_futu).length}只`;mrows();
$('cl-meta').textContent=`最近事件 ${date(data.cl20.latest_event_at)} 北京 · ${data.cl20.rows.length}条`;const selected=$('cl-kind').value;$('cl-kind').replaceChildren(new Option('全部状态',''));for(const k of new Set(data.cl20.rows.map(r=>r.kind)))$('cl-kind').append(new Option(k,k));$('cl-kind').value=selected;clrows();
$('structure-meta').textContent=`${date(data.structure.asof,'America/New_York')} ET`;$('structure-status').textContent=data.structure.status;$('structure-content').replaceChildren();for(const r of data.structure.rows)$('structure-content').append(n('p',`${r.name} ${r.code} · ${r.change} · ${r.board_name||'行业待核验'}`));
$('post-meta').textContent=`${data.post.date} · 完整RTH日线`;$('post-rows').replaceChildren();for(const r of data.post.rows){const tr=n('tr');tr.append(stock(r),n('td',r.status),...['close','confirmation','invalidation','reduce','target'].map(k=>n('td',price(r[k]),k==='invalidation'?'em-risk':'')),n('td',`第${r.review}个交易日`));$('post-rows').append(tr)}if(!data.post.rows.length)empty($('post-rows'),8)}
// Tiny Markdown renderer: source text never enters innerHTML; links are http(s) only.
function inline(el,text){const re=/\*\*([^*]+)\*\*|\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g;let at=0,m;while((m=re.exec(text))){el.append(document.createTextNode(text.slice(at,m.index)));if(m[1])el.append(n('strong',m[1]));else{const a=n('a',m[2]);a.href=m[3];a.target='_blank';a.rel='noopener noreferrer';el.append(a)}at=re.lastIndex}el.append(document.createTextNode(text.slice(at)))}
function markdown(body,text){body.replaceChildren();const lines=text.split('\n');let table=null;for(let line of lines){line=line.trim();if(!line||/^# /.test(line)||/^\|[\s|:\-]+\|$/.test(line))continue;if(line.startsWith('|')){if(!table){const wrap=n('div',null,'table-wrap');table=n('table');wrap.append(table);body.append(wrap)}const tr=n('tr');for(const cell of line.replace(/^\||\|$/g,'').split('|')){const td=n(table.children.length?'td':'th');inline(td,cell.trim());tr.append(td)}table.append(tr);continue}table=null;let el;if(/^#{2,3} /.test(line))el=n('h3',line.replace(/^#+\s*/,''));else{el=n('p');inline(el,line.replace(/^[-*] /,'• '));if(/风险偏好/.test(line))el.className='conclusion-block'}body.append(el)}}
async function refresh(){const results=await Promise.allSettled(['data.json','reports.json'].map(async f=>{const r=await fetch('./'+f,{cache:'no-store'});if(!r.ok)throw Error();return r.json()}));let failures=0;if(results[0].status==='fulfilled'&&results[0].value.schema_version===1){data=results[0].value;render()}else failures++;if(results[1].status==='fulfilled'&&results[1].value.schema_version===1){reports=results[1].value;$('pre-meta').textContent=`${reports.pre.date} · 原报告 · ${reports.pre.frozen}`;markdown($('pre-content'),reports.pre.markdown)}else failures++;$('load-status').textContent=failures?'部分数据读取失败，稍后重试':'各栏目按源日期更新';$('ny-date').textContent=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
for(const id of ['m-search','m-scope'])$(id).addEventListener(id.endsWith('search')?'input':'change',()=>data&&mrows());for(const id of ['cl-search','cl-kind'])$(id).addEventListener(id.endsWith('search')?'input':'change',()=>data&&clrows());refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);
})();
