const state={data:null,view:'overview',query:'',sectorType:'industry'};
const titles={overview:['复盘总览','用结构化数据看懂今天的市场，而不是被涨跌牵着走。'],indices:['大盘指数','指数收盘与近 100 个交易日日 K。'],sentiment:['市场情绪','全市场涨跌宽度、涨跌分布与情绪温度。'],sectors:['板块强弱','行业与概念板块按当日涨跌幅排序。'],flows:['资金流向','未核验时不展示演示数据。'],limits:['涨跌停池','按不同板块涨跌停制度识别。'],watchlist:['冰神观察池','原 17 只观察名单的真实收盘快照。'],institutions:['机构持仓','季度低频数据模块。'],chips:['筹码分析','股东户数低频数据模块。'],methodology:['数据口径','数据源、覆盖率、刷新时间与边界。']};
const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:2}),pct=n=>`${Number(n)>0?'+':''}${Number(n).toFixed(2)}%`,tone=n=>Number(n)>=0?'up':'down';
function amount(n){n=Number(n||0);return Math.abs(n)>=1e8?`${(n/1e8).toFixed(1)}亿`:Math.abs(n)>=1e4?`${(n/1e4).toFixed(0)}万`:fmt(n)}
function title(n,t,s=''){return `<div class="panel-title"><div><span class="num">${n}</span><h2>${t}</h2>${s?`<small>${s}</small>`:''}</div></div>`}
function stats(){const d=state.data,m=d.market,l=d.limits;return `<div class="stat-grid"><article><span>上涨家数</span><b class="up">${fmt(m.up)}</b><small>覆盖 ${fmt(m.coverage)} 只</small></article><article><span>下跌家数</span><b class="down">${fmt(m.down)}</b><small>平盘 ${fmt(m.flat)} 只</small></article><article><span>涨停 / 跌停</span><b><em class="up">${l.up}</em> / <em class="down">${l.down}</em></b><small>按板块阈值识别</small></article><article><span>全市场成交额</span><b>${d.display.amount}</b><small>有效快照汇总</small></article></div>`}
function indicesStrip(){return `<section class="index-strip">${state.data.indices.map(x=>`<article><span>${x.name}</span><small>${x.code}</small><b>${fmt(x.value)}</b><em class="${tone(x.change)}">${pct(x.change)}</em></article>`).join('')}</section>`}
function bars(rows,green=false){const max=Math.max(.01,...rows.map(x=>Math.abs(x.change)));return `<div class="bars">${rows.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="bar-track"><i class="${green?'green':''}" style="width:${Math.max(5,Math.abs(x.change)/max*100)}%"></i></div><b class="${tone(x.change)}">${pct(x.change)}</b></div>`).join('')}</div>`}
function stocks(rows){const q=state.query.toLowerCase(),a=rows.filter(x=>!q||`${x.name}${x.code}${x.industry||''}`.toLowerCase().includes(q));if(!a.length)return unavailable('没有匹配项','请尝试股票简称或 6 位代码。',false);const max=Math.max(1,...a.map(x=>Math.abs(x.change)));return `<div class="stock-list">${a.map((x,i)=>`<div class="stock-row" data-stock='${JSON.stringify(x).replaceAll("'","&#39;")}'><span class="rank">${String(i+1).padStart(2,'0')}</span><b>${x.name}<small>${x.code}</small></b><i class="mini-bar" style="width:${Math.max(8,Math.abs(x.change)/max*100)}%"></i><strong class="${tone(x.change)}">${pct(x.change)}</strong><small>${amount(x.amount)}</small></div>`).join('')}</div>`}
function distribution(){const a=state.data.market.distribution,max=Math.max(...a.map(x=>x.count));return `<div class="distribution">${a.map(x=>`<div class="dist-item"><b>${x.count}</b><i class="dist-bar" style="height:${Math.max(3,x.count/max*86)}%"></i><span>${x.bucket}</span></div>`).join('')}</div>`}
function overview(){const d=state.data,m=d.market,copy=m.sentiment>=70?'情绪偏热，注意高位分化':m.sentiment>=50?'情绪中性偏活跃，结构分化':'情绪偏弱，优先控制风险';return `<section class="hero-grid"><article class="sentiment-card"><div><div class="eyebrow">今日市场温度</div><div class="score">${m.sentiment}<small>/ 100</small></div></div><div class="score-copy"><b>${copy}</b><span>由涨跌宽度、涨跌停数量与平均涨幅计算。</span></div><div class="meter"><i style="width:${m.sentiment}%"></i></div><div class="meter-label"><span>冰点</span><span>中性</span><span>亢奋</span></div></article>${stats()}</section>${indicesStrip()}<section class="two-col"><article class="panel">${title('01','行业领涨','OpenD 行业板块')}${bars(d.sectors.industryRise.slice(0,8))}</article><article class="panel">${title('02','涨幅居前','全市场')}${stocks(d.rankings.gainers.slice(0,8))}</article></section><article class="panel wide">${title('03','涨跌幅分布','有效股票快照')}${distribution()}</article>`}
function kline(){const a=state.data.kline.bars.slice(-100),W=1200,H=360,L=18,R=58,T=16,B=65,ph=H-T-B,ps=a.flatMap(x=>[x.high,x.low]),lo=Math.min(...ps),hi=Math.max(...ps),step=(W-L-R)/a.length,cw=Math.max(2,step*.52),y=v=>T+(hi-v)/(hi-lo)*ph,mv=Math.max(...a.map(x=>x.volume));let s='';for(let i=0;i<5;i++){let yy=T+ph*i/4,v=hi-(hi-lo)*i/4;s+=`<line class="grid-line" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"/><text class="axis-label" x="${W-R+8}" y="${yy+3}">${v.toFixed(0)}</text>`}a.forEach((x,i)=>{let xx=L+step*i+step/2,up=x.close>=x.open,c=up?'candle-up':'candle-down',yo=y(x.open),yc=y(x.close),vh=x.volume/mv*48;s+=`<line class="${c}" x1="${xx}" y1="${y(x.high)}" x2="${xx}" y2="${y(x.low)}"/><rect class="${c}" x="${xx-cw/2}" y="${Math.min(yo,yc)}" width="${cw}" height="${Math.max(1,Math.abs(yc-yo))}"/><rect class="${up?'volume-up':'volume-down'}" x="${xx-cw/2}" y="${H-vh}" width="${cw}" height="${vh}"/>`});return `<div class="kline-wrap"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${s}</svg></div>`}
function indexView(){return `${indicesStrip()}<article class="panel wide">${title('01','上证指数日 K 线','近 100 个交易日 · 不复权')}${kline()}</article><article class="panel wide">${title('02','指数涨跌统计')}${bars([...state.data.indices].sort((a,b)=>b.change-a.change),state.data.indices.every(x=>x.change<0))}</article>`}
function sentiment(){return `<section class="hero-grid"><article class="sentiment-card"><div><div class="eyebrow">情绪温度计</div><div class="score">${state.data.market.sentiment}<small>/ 100</small></div></div><div class="score-copy"><b>平均涨跌 ${pct(state.data.market.averageChange)}</b><span>规则合成值，不是买卖信号。</span></div><div class="meter"><i style="width:${state.data.market.sentiment}%"></i></div><div class="meter-label"><span>冰点</span><span>中性</span><span>亢奋</span></div></article>${stats()}</section><article class="panel wide">${title('01','涨跌幅分布')}${distribution()}</article><section class="two-col"><article class="panel">${title('02','涨幅 TOP15')}${stocks(state.data.rankings.gainers)}</article><article class="panel">${title('03','跌幅 TOP15')}${stocks(state.data.rankings.losers)}</article></section>`}
function sectors(){const p=state.sectorType,r=state.data.sectors[`${p}Rise`],f=state.data.sectors[`${p}Fall`],name=p==='industry'?'行业板块':'概念题材',all=[...r,...f].filter((x,i,a)=>a.findIndex(y=>y.code===x.code)===i).sort((a,b)=>b.change-a.change);return `<div class="segmented"><button data-sector="industry" class="${p==='industry'?'active':''}">行业板块</button><button data-sector="concept" class="${p==='concept'?'active':''}">概念题材</button></div><section class="two-col"><article class="panel">${title('01',`${name}涨幅前列`)}${bars(r)}</article><article class="panel">${title('02',`${name}跌幅前列`)}${bars(f,true)}</article></section><article class="panel wide table-panel">${title('03','板块明细')}<div class="data-table sector-table"><div class="tr th"><span>#</span><span>板块</span><span>涨跌幅</span><span>成交额</span></div>${all.map((x,i)=>`<div class="tr"><span>${i+1}</span><b>${x.name}</b><strong class="${tone(x.change)}">${pct(x.change)}</strong><span>${amount(x.amount)}</span></div>`).join('')}</div></article>`}
function unavailable(h,p,link=true){return `<article class="panel unavailable"><span>!</span><h3>${h}</h3><p>${p}</p>${link?'<a href="#methodology">查看数据接入边界 →</a>':''}</article>`}
function flows(){return `<div class="flow-total"><b class="neutral">未接入</b><span>全市场主力净流入</span><small>不以局部样本推算全市场</small></div><section class="two-col">${unavailable('个股资金流暂未接入','免费稳定源无法提供可重复核验的全市场主力净流入；接入 Choice、iFinD 或 Wind 后可补齐。')}${unavailable('板块资金流暂未接入','不会把涨跌额或成交额伪装成主力资金。')}</section>`}
function limits(){const l=state.data.limits,up=l.streaks.flatMap(x=>x.stocks);return `${stats()}<section class="two-col"><article class="panel">${title('01','今日涨停池',`${l.up} 只 · 连板高度未接入`)}<div class="limit-cloud">${up.map(x=>`<button class="limit-chip" data-stock='${JSON.stringify(x).replaceAll("'","&#39;")}'>${x.name}<small>${pct(x.change)}</small></button>`).join('')}</div></article><article class="panel">${title('02','跌幅居前',`${l.down} 只跌停`)}${stocks(state.data.rankings.losers)}</article></section><article class="panel wide">${title('03','识别口径','主板10% / ST 5% / 创业板与科创板20% / 北交所30%')}<p style="color:var(--muted);font-size:11px;line-height:1.8">按 OpenD 收盘涨跌幅识别，容差 0.12 个百分点。封单额、开板次数、涨停原因与连续板高度当前留空。</p></article>`}
function watch(){const a=state.data.watchlist.filter(x=>!state.query||`${x.name}${x.code}`.includes(state.query));return `<article class="panel table-panel">${title('01','冰神 A 股观察池',`${state.data.watchlist.length}/17 只有效收盘快照 · 仅为研究记录`)}<div class="data-table watch-table"><div class="tr th"><span>#</span><span>证券</span><span>现价</span><span>涨跌幅</span><span>成交额</span><span>富途代码</span></div>${a.map((x,i)=>`<div class="tr" data-stock='${JSON.stringify(x).replaceAll("'","&#39;")}'><span>${i+1}</span><b>${x.name}</b><span>${fmt(x.price)}</span><strong class="${tone(x.change)}">${pct(x.change)}</strong><span>${amount(x.amount)}</span><span>${x.futuCode}</span></div>`).join('')}</div><div class="legacy-links"><a href="downloads/冰神A股名单_富途格式.csv" download>下载 CSV</a><a href="downloads/富途OpenD代码_每行一个.txt" download>下载代码 TXT</a><a href="../code/">指标代码中心</a></div></article>`}
function method(){const d=state.data;return `<section class="source-grid"><article class="source-card"><h3>数据状态 <span class="status-badge">已核验收盘</span></h3><p><strong>交易日：</strong>${d.data_date}<br><strong>生成：</strong>${d.generated_at}<br><strong>有效覆盖：</strong>${fmt(d.market.coverage)} 只<br><strong>频率：</strong>工作日收盘后一次</p></article><article class="source-card"><h3>来源与职责</h3><ul>${d.sources.map(x=>`<li><strong>${x.name}</strong>：${x.role}（${x.access}）</li>`).join('')}</ul></article><article class="source-card"><h3>当前边界 <span class="status-badge warn">未接入</span></h3><p>全市场主力净流入、机构持仓、股东户数、封单额、开板次数、涨停原因和连板高度未接入，不以演示数据补位。</p></article><article class="source-card"><h3>使用边界</h3><p>本站为盘后研究工具，不提供交易、下单、账户、登录或个性化荐股。结论需结合公告独立核验。</p></article></section>`}
function render(){if(!state.data)return;let [h,s]=titles[state.view]||titles.overview;$('#page-title').textContent=h;$('#page-subtitle').textContent=s;document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===state.view));let v={overview:overview,indices:indexView,sentiment,sectors,flows,limits,watchlist:watch,institutions:()=>unavailable('机构持仓数据未接入',state.data.slowData.institutions.note),chips:()=>unavailable('筹码数据未接入',state.data.slowData.chips.note),methodology:method}[state.view]||overview;$('#view').innerHTML=v();document.querySelectorAll('[data-sector]').forEach(b=>b.onclick=()=>{state.sectorType=b.dataset.sector;render()});document.querySelectorAll('[data-stock]').forEach(x=>x.onclick=()=>show(JSON.parse(x.dataset.stock)))}
function show(x){$('#detail-body').innerHTML=`<div class="detail-content"><p>${x.futuCode||x.code}</p><h2>${x.name}</h2><div class="detail-metrics"><div><span>收盘价</span><b>${fmt(x.price)}</b></div><div><span>当日涨跌</span><b class="${tone(x.change)}">${pct(x.change)}</b></div><div><span>成交额</span><b>${amount(x.amount)}</b></div><div><span>换手率</span><b>${x.turnover==null?'—':pct(x.turnover)}</b></div><div><span>数据日</span><b>${state.data.data_date}</b></div><div><span>状态</span><b>已核验收盘</b></div></div></div>`;$('#detail').showModal()}
function nav(){let h=location.hash.slice(1)||'overview';state.view=titles[h]?h:'overview';render();$('#sidebar').classList.remove('open')}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2000)}
async function boot(){try{let r=await fetch(`data.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);state.data=await r.json();if(state.data.market.status!=='verified_close')throw Error('not close');$('#data-date').textContent=state.data.data_date;$('#side-date').textContent=`${state.data.data_date} · ${fmt(state.data.market.coverage)} 只`;$('#loading').hidden=true;$('#view').hidden=false;nav()}catch(e){console.error(e);$('#loading').hidden=true;$('#error').hidden=false}}
window.addEventListener('hashchange',nav);$('#search').oninput=e=>{state.query=e.target.value.trim();render()};$('#menu-button').onclick=()=>$('#sidebar').classList.toggle('open');$('#export').onclick=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=`盘鉴-A股收盘-${state.data.data_date}.json`;a.click();URL.revokeObjectURL(u);toast('数据已导出')};$('.dialog-close').onclick=()=>$('#detail').close();boot();
