'use strict';
(()=>{
 let feed;
 const el=id=>document.getElementById(id), node=(tag,value,cls)=>{const n=document.createElement(tag);n.textContent=value??'—';if(cls)n.className=cls;return n};
 const ratio=v=>typeof v==='number'?v.toFixed(2)+'×':'—';
 const stamp=v=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
 function empty(body,cols){const row=document.createElement('tr'),cell=node('td','没有匹配记录');cell.colSpan=cols;row.append(cell);body.append(row)}
 function stocks(id,key){const d=feed[key],q=el(id+'-search').value.trim().toLowerCase(),body=el(id+'-rows');body.replaceChildren();el(id+'-meta').textContent=`${d.date} · ${d.rows.length}只候选 · 富途${d.rows.filter(r=>r.in_futu).length}只已核验`;
 for(const r of d.rows.filter(r=>(r.code+r.name).toLowerCase().includes(q))){const tr=document.createElement('tr'),td=document.createElement('td');td.append(node('b',r.name),node('small',r.code));if(r.in_futu)td.append(node('small','富途名单','feed-category'));tr.append(td,node('td',r.category,'feed-category'),node('td',r.key_date),node('td',ratio(r.volume_ratio)),node('td',[r.stage,r.shape].filter(Boolean).join(' · ')));body.append(tr)}if(!body.children.length)empty(body,5)}
 function signals(){const d=feed.cl20,q=el('cl20-search').value.trim().toLowerCase(),market=el('cl20-market').value,kind=el('cl20-kind').value,body=el('cl20-rows');const rows=d.rows.filter(r=>(!market||r.market===market)&&(!kind||r.kind===kind)&&(r.code+r.name).toLowerCase().includes(q));body.replaceChildren();el('cl20-meta').textContent=`扫描 ${stamp(d.updated_at)} · 已核验 ${d.verified}/${d.attempted}${d.failed?' · '+d.failed+'只未核验':''}`;el('cl20-count').textContent=rows.length+'条 / 最近'+d.rows.length+'条';
 for(const r of rows){const tr=document.createElement('tr'),stock=document.createElement('td'),signal=document.createElement('td'),revoked=/撤销|修订/.test(r.kind);stock.append(node('b',r.name),node('small',r.code+' · '+({CN:'A股',US:'美股',HK:'港股'}[r.market])));signal.append(node('b',r.label,revoked?'signal-muted':r.label?.includes('B')?'signal-buy':'signal-sell'));signal.append(node('small',revoked?'原信号已变更':r.label?.includes('B')?'买入观察':'减仓 / 止盈观察'));tr.append(node('td',stamp(r.detected_at)),stock,signal,node('td',r.kind,revoked?'signal-muted':'feed-category'),node('td',r.price),node('td',r.pivot_time),node('td',r.delivery));body.append(tr)}if(!rows.length)empty(body,7)}
 async function refresh(){try{const response=await fetch('./observation-feeds.json',{cache:'no-store'});if(!response.ok)throw Error();const next=await response.json();if(next.schema_version!==1)throw Error();feed=next;stocks('observe','a');stocks('mobserve','m');signals();el('observeTag').textContent=`A观察 ${feed.a.rows.length}只 · ${feed.a.date} / M观察 ${feed.m.rows.length}只 · ${feed.m.date}`;}catch{for(const id of ['observe','mobserve','cl20'])el(id+'-meta').textContent=feed?'刷新失败，保留上次快照':'数据暂未取得，请稍后重试'}}
 for(const [id,key] of [['observe','a'],['mobserve','m']])el(id+'-search').addEventListener('input',()=>feed&&stocks(id,key));for(const id of ['cl20-search','cl20-market','cl20-kind'])el(id).addEventListener(id.endsWith('search')?'input':'change',()=>feed&&signals());refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);
})();
