'use strict';
const $=s=>document.querySelector(s), main=$('#main');
const views={a:[['midterm','交易计划'],['observe','A / B / C 候选'],['cl20','30分钟信号'],['pre','盘前原文'],['post','盘后原文'],['rules','执行规则']],us:[['tonight','交易计划'],['replay','模拟盘回放'],['mobserve','A / B / C 候选'],['cl20','30分钟信号'],['structure','半小时结构'],['pre','盘前原文'],['rules','执行规则']]};
const paths={replay:'replay.json',replayABC:'replay-abc.json',a:'a-share-workbench/observation-feeds.json',u:'us-share-workbench/data.json',c:'a-share-workbench/daily-selection.json',mid:'a-share-workbench/midterm.json',ar:'a-share-workbench/reports.json',ur:'us-share-workbench/reports.json',sync:'sync-status.json',schedule:'schedule.json'};
let data={},failures=[],lane='all',search='',signalDate='',fee=0,loaded=false,signature='';
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e};
const money=v=>Number.isFinite(v)?v.toFixed(2):'未生成';
const percent=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(2)}%`:'未计算';
const date=(v,tz='Asia/Shanghai')=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'未取得';
const today=tz=>new Intl.DateTimeFormat('sv-SE',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const ret=TradeMath.targetReturn;
function add(...els){main.append(...els)}
function heading(title,meta){const h=n('header',null,'page-head');h.append(n('h1',title),n('div',meta,'meta'));add(h)}
function cells(primary,secondary,cls){const td=n('td');td.append(n('div',primary,cls));if(secondary)td.append(n('small',secondary));return td}
function stock(r){const td=cells(r.name||r.stock,r.code||r.role);td.className='stock';td.firstChild.style.fontWeight='650';return td}
function table(headers,rows){const wrap=n('div',null,'table-wrap'),t=n('table'),thead=n('thead'),tr=n('tr'),body=n('tbody');for(const h of headers)tr.append(n('th',h));thead.append(tr);t.append(thead,body);wrap.append(t);for(const row of rows){[...row.children].forEach((td,i)=>td.dataset.label=headers[i]);body.append(row);}if(!rows.length){const row=n('tr'),cell=n('td','当前筛选没有记录','empty');cell.colSpan=headers.length;row.append(cell);body.append(row)}return wrap}
function detail(label,sections){const button=n('button',label,'link-button');button.type='button';button.setAttribute('aria-expanded','false');button.onclick=()=>{const row=button.closest('tr');if(row.nextSibling?.classList.contains('detail-row')){row.nextSibling.remove();button.setAttribute('aria-expanded','false');return}const tr=n('tr',null,'detail-row'),td=n('td');td.colSpan=row.children.length;const grid=n('div',null,'detail-grid');for(const [title,lines] of sections){const part=n('section');part.append(n('h3',title));for(const l of lines.filter(Boolean))part.append(n('p',l));grid.append(part)}td.append(grid);tr.append(td);row.after(tr);button.setAttribute('aria-expanded','true')};return button}
function filterbar(options,draw){const bar=n('div',null,'toolbar'),tabs=n('div',null,'tabs');for(const [value,text] of options){const b=n('button',text);b.setAttribute('aria-pressed',String(lane===value));b.onclick=()=>{lane=value;draw()};tabs.append(b)}const label=n('label',null,'push');label.append(n('span','股票'));const input=n('input');input.type='search';input.placeholder='名称或代码';input.value=search;input.oninput=()=>{search=input.value;draw(true)};label.append(input);bar.append(tabs,label);return bar}
function inline(el,text){const re=/\*\*([^*]+)\*\*|\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g;let at=0,m;while((m=re.exec(text))){el.append(document.createTextNode(text.slice(at,m.index)));if(m[1])el.append(n('strong',m[1]));else{const a=n('a',m[2]);a.href=m[3];a.target='_blank';a.rel='noopener noreferrer';el.append(a)}at=re.lastIndex}el.append(document.createTextNode(text.slice(at)))}
function markdown(text){const box=n('article',null,'report');let tbl=null;for(const raw of text.split('\n')){const line=raw.trim();if(!line)continue;if(/^\|[\s|:\-]+\|$/.test(line))continue;if(line.startsWith('|')){if(!tbl){const wrap=n('div',null,'table-wrap');tbl=n('table');wrap.append(tbl);box.append(wrap)}const tr=n('tr');for(const v of line.replace(/^\||\|$/g,'').split('|')){const td=n(tbl.children.length?'td':'th');inline(td,v.trim());tr.append(td)}tbl.append(tr);continue}tbl=null;const h=line.match(/^(#{1,6})\s+(.+)/);const el=n(h?'h'+Math.min(h[1].length,3):'p');inline(el,h?h[2]:line);box.append(el)}return box}
function usPlans(){const u=data.u,t=u.tonight,sys=u.trading_system;heading('美股交易计划',`计划报价 ${date(t.generated_at_bj)} 北京 · 日线 ${t.daily_as_of} RTH · USD`);add(n('div',t.market_gate_closed?'市场门关闭 · 当前只观察，价格计划待条件满足后执行':'市场门已通过 · 逐股等待入场确认','gate'));
const bar=n('div',null,'toolbar');const label=n('label','单边费用 / 滑点（基点）');const input=n('input');input.type='number';input.min='0';input.max='1000';input.step='1';input.value=fee;input.oninput=()=>{fee=Math.min(1000,Math.max(0,Number(input.value)||0));document.querySelectorAll('tr[data-entry]').forEach(tr=>{const e=Number(tr.dataset.entry),s=Number(tr.dataset.stop),r=Number(tr.dataset.reduce),t=Number(tr.dataset.target);const loss=cells(money(s),percent(ret(e,s,fee)),'loss');loss.dataset.label='止损 / 计划损失';tr.children[3].replaceWith(loss);const gain=cells(percent(ret(e,t,fee)),`首档 ${percent(ret(e,r,fee))} · 各半 ${percent(ret(e,(r+t)/2,fee))} · 盈亏比 ${e>s?(ret(e,t,fee)/-ret(e,s,fee)).toFixed(2):'不适用'}`,'gain');gain.dataset.label='预估收益率';tr.children[5].replaceWith(gain)})};label.append(input);bar.append(label,n('span','收益按买入确认价测算；不含分红、税费及汇率变化','meta'));add(bar);
const rows=Object.entries(sys.plans).map(([code,p])=>{const live=t.candidates.find(r=>r.code===code),entry=live?.buy_confirmation??p.entry.confirmation_price,stop=live?.invalidation??p.exit.invalidation_price,reduce=live?.first_reduce??p.exit.reduce_price,target=live?.final_target??p.exit.final_target_price,initial=live?.initial_position_pct??p.entry.initial_position_pct;const tr=n('tr');Object.assign(tr.dataset,{entry,stop,reduce,target});tr.append(stock({name:p.name,code}),cells(money(live?.quote??p.latest_close),live?'盘前快照':'日线收盘'),cells(money(entry),live?'最高接受 '+money(live.maximum_acceptable):'回踩区 '+p.entry.pullback_zone.map(money).join('—'),'num'),cells(money(stop),percent(ret(entry,stop,fee)),'loss'),cells(money(reduce)+' / '+money(target),'第一目标减半 / 最终退出','num'),cells(percent(ret(entry,target,fee)),`首档 ${percent(ret(entry,reduce,fee))} · 各半 ${percent(ret(entry,(reduce+target)/2,fee))} · 盈亏比 ${entry>stop?(ret(entry,target,fee)/-ret(entry,stop,fee)).toFixed(2):'不适用'}`,'gain'),cells(`首笔 ${initial}% · 上限 ${p.position.max_position_pct}%`,`风险预算 ${p.position.risk_budget_pct_of_equity}% · ${p.holding.max_trading_days}日上限`));const state=cells(t.market_gate_closed?'只观察':p.status,`第${p.holding.review_trading_day}个交易日复核`,'state');state.append(detail('执行条件', [['买入与仓位',[live?'第一观察 '+money(live.first_observation):null,p.entry.rule,live?.intraday_confirmation,p.position.shares_formula]],['卖出与持有',[...p.exit.rules,p.holding.time_stop]],['计划来源与门槛',[`完整日线 ${p.as_of} · ${p.sources.map(x=>({A:'关K回调',B:'日线回稳',C:'主升延续'}[x])).join(' / ')}`,`相对强度：${p.gates.relative_strength_ok?'通过':'未通过'}；过热：${p.gates.overheated?'是':'否'}`,live?`盘中确认参考 ${date(t.generated_at_bj)} 北京；${live.action}`:'今晚尚未入选优先执行名单']]]));tr.append(state);return tr});const sheet=table(['股票','价格 / 时点','买入确认价','止损 / 计划损失','减仓 / 卖出目标','预估收益率','计划仓位 / 时限','当前状态'],rows);sheet.classList.add('plan-table');add(sheet);}
function aPlans(){const m=data.mid;heading('A股交易计划',`源规划 ${date(m.as_of)} 北京 · CNY`);const rows=m.rows.map(r=>{const tr=n('tr');tr.append(stock(r),cells(r.close,'源规划收盘'),cells('待生成计划','买卖价未成对给出','state'),cells('待生成','新信号后确定止损'),cells('未计算','缺少有效买入与卖出价'),cells(r.position_limit,r.holding));const st=cells('等待模型买点',r.role,'state');st.append(detail('观察区与条件',[['技术观察',[r.observation,r.pressure]],['入场条件',[r.state,r.next]],['身份与仓位',[r.industry,`仓位上限 ${r.position_limit}`,r.holding]]]));tr.append(st);return tr});const sheet=table(['股票 / 身份','参考收盘','买入 / 卖出价','止损价','预估收益率','计划仓位 / 持有','状态 / 详情'],rows);sheet.classList.add('plan-table');add(sheet);add(n('p','这份源规划只给观察区，尚无可执行买卖价格；下方可用自行设定的价格测算收益。','note'));scenario();const link=n('a','查看完整规划原文','link-button');link.href='#a/original';add(link);}
function scenario(){const wrap=n('section',null,'scenario');wrap.append(n('h2','价格情景测算'));const bar=n('div',null,'toolbar'),inputs={};for(const [key,title] of [['buy','假设买入价'],['sell','假设卖出价'],['stop','假设止损价'],['qty','股数'],['bps','单边费用（基点）']]){const label=n('label',title),input=n('input');input.type='number';input.min='0';input.step=key==='qty'?'1':'0.01';input.placeholder=key==='bps'?'0':'输入';label.append(input);bar.append(label);inputs[key]=input}const out=n('output','输入买入、卖出和止损价后计算。');const calc=()=>{const v=Object.fromEntries(Object.entries(inputs).map(([k,i])=>[k,Number(i.value)]));if(!(v.buy>0&&v.sell>0&&v.stop>0&&v.bps<10000)){out.textContent='输入买入、卖出和止损价后计算。';return}const profit=v.sell*(1-v.bps/10000)-v.buy*(1+v.bps/10000),risk=v.buy*(1+v.bps/10000)-v.stop*(1-v.bps/10000);out.textContent=`情景收益 ${percent(ret(v.buy,v.sell,v.bps))} · 止损情景 ${percent(ret(v.buy,v.stop,v.bps))} · 盈亏比 ${risk>0?(profit/risk).toFixed(2)+' : 1':'不适用'}${v.qty>0?' · 预估收益金额 '+money(profit*v.qty):''}`};Object.values(inputs).forEach(i=>i.oninput=calc);wrap.append(bar,out,n('p','仅计算输入价格的情景结果，不生成买卖信号，也不保存为交易指令。','note'));add(wrap)}
function candidates(market,keepFocus=false){const isA=market==='a',d=isA?data.a.a:data.u.m,all=isA?[...d.rows,...data.c.rows.map(r=>({...r,category:'C'}))]:d.rows;main.replaceChildren();heading((isA?'A股':'美股')+'日线候选',`${d.date} ${isA?'A/B 收盘 · C类 '+data.c.as_of.slice(0,10):'完整 RTH'} · 分类独立展示`);const options=[['all','全部'],...['A','B','C'].map(k=>[k,`${k} · ${{A:'关K回调',B:'日线回稳',C:'主升延续'}[k]}  ${all.filter(r=>r.category.split(' / ').includes(k)).length}`])];add(filterbar(options,k=>candidates(market,k)));const rows=all.filter(r=>(lane==='all'||r.category.split(' / ').includes(lane))&&((r.name||'')+r.code).toLowerCase().includes(search.toLowerCase())).map(r=>{const tr=n('tr');tr.append(stock(r));if(lane==='A'){tr.append(cells(r.key_date,'关K日期'),cells(r.volume_ratio?`${r.volume_ratio.toFixed(2)}×`:'未核验','关K / 前日量'));}else if(isA&&lane==='B'){tr.append(cells(r.bottom_date,'结构底日期'),cells(money(r.structural_invalidation),'结构失效线'));}else if(isA&&lane==='C'){tr.append(cells(r.setups.join(' / '),r.momentum.stage),cells(money(r.research_invalid_below),'研究失效线'));}else tr.append(cells(r.category.split(' / ').map(k=>`${k} · ${{A:'关K回调',B:'日线回稳',C:'主升延续'}[k]}`).join(' / ')),cells(isA?money(r.close):r.stage,isA?'收盘':''));tr.append(cells(r.stage,r.shape||r.execution),cells(r.in_futu?'已同步富途':r.category==='C'&&isA?'第三类独立名单':'候选',null,r.in_futu?'tag':''));return tr});const headers=['股票',...(lane==='A'?['关K日期','量比']:isA&&lane==='B'?['底部结构','失效依据']:isA&&lane==='C'?['形态 / 动能','失效依据']:['类型','收盘 / 阶段']),'当前状态','名单'];add(table(headers,rows));if(keepFocus){const input=$('input[type=search]');input.focus();input.setSelectionRange(search.length,search.length)}}
function signals(market){const isA=market==='a',d=isA?data.a.cl20:data.u.cl20,tz=isA?'Asia/Shanghai':'America/New_York',selected=signalDate||today(tz);heading((isA?'A股':'美股')+'30分钟信号',`最近源记录 ${date(d.updated_at||d.latest_event_at)} 北京`);const bar=n('div',null,'toolbar'),label=n('label',isA?'交易日期（北京）':'交易日期（纽约）'),input=n('input');input.type='date';input.value=selected;input.onchange=()=>{signalDate=input.value;render()};label.append(input);const btn=n('button','今天');btn.onclick=()=>{signalDate='';render()};bar.append(label,btn,n('span','历史记录按日期查询','meta'));add(bar);const rows=d.rows.filter(r=>r.detected_at&&TradeMath.signalDay(r.detected_at,tz)===selected).map(r=>{const tr=n('tr');tr.append(cells(date(r.detected_at,tz).slice(11),'发现时间'),stock(r),cells(r.label+(r.label?.includes('B')?' · 买入观察':r.label?.includes('S')?' · 卖出观察':''),r.kind,/撤销|修订/.test(r.kind)?'muted':'tag'),cells(money(r.price),'信号记录价'),cells(r.bar_end||'未记录','确认K线时间'),cells(r.pivot_time,'结构起点'));return tr});add(table(['发现时间','股票','信号 / 变化','记录价','确认K线','结构起点'],rows));if(!rows.length)add(n('p',`${selected} 尚无已同步的信号记录。`,'note'));}
function rules(market){heading((market==='a'?'A股':'美股')+'执行规则','源计划规则');if(market==='a'){add(markdown(data.mid.management));return}const s=data.u.trading_system,r=s.portfolio_rules;add(table(['单笔风险','总风险','最多持有','每天最多新开'],[(()=>{const tr=n('tr');[r.single_trade_risk_pct+'%',r.max_total_risk_pct+'%',r.max_open_positions+'只',r.max_new_positions_per_day+'只'].forEach(v=>tr.append(cells(v)));return tr})()]));add(n('p',r.execution),n('p',r.priority));const rows=Object.entries(s.plans).map(([code,p])=>{const tr=n('tr');tr.append(stock({name:p.name,code}),cells(p.entry.rule),cells(p.exit.rules.join('；')),cells(p.holding.time_stop),cells(p.position.shares_formula));return tr});add(table(['股票','买入规则','卖出规则','时间退出','仓位计算'],rows));}
function report(market,key){const d=market==='a'?data.ar[key]:data.ur.pre;heading((market==='a'?'A股':'美股')+(key==='post'?'盘后原文':'盘前原文'),d.date+' · 完整原文');if(d.original_url){const frame=n('iframe',null,'original');frame.title=(key==='post'?'盘后':'盘前')+'完整原报告';frame.sandbox='allow-same-origin allow-popups allow-popups-to-escape-sandbox';frame.src=d.original_url;add(frame)}else add(markdown(d.markdown||d.body||''));}

function replayPage(){
 const abc=location.hash.endsWith('replay-abc');const r=abc?data.replayABC:data.replay;if(!r)throw Error('回放结果未取得');const s=r.summary;heading(r.title,`${r.start} — ${r.end} · USD`);const modes=n('p');for(const [label,url] of [['每日轮动模拟','#us/replay'],['ABC规则对照','#us/replay-abc']]){const a=n('a',label,'link-button');a.href=url;modes.append(a,document.createTextNode('　'))}add(modes);
 add(n('p',`${Object.keys(r.universe).length} 只历史样本 · ${abc?'ABC日线买点':'独立轮动规则，每天最多新买1只、持满5日轮换'} · 目标持有4–5只。`,'note'));
 const summary=n('tr');[money(s.initial_capital),money(s.equity),percent(s.return_pct),percent(s.max_drawdown_pct),money(s.realized_pnl),String(s.closed_trades)].forEach((v,i)=>summary.append(cells(v,null,i===2?(s.return_pct>=0?'gain':'loss'):'')));
 const metrics=table(['初始资金','期末权益','模拟账户收益率','最大回撤','已实现盈亏','完整交易'],[summary]);metrics.classList.add('plan-table','replay-metrics');add(metrics);
 const cadence=n('tr');[s.target_positions??'4–5',Number(s.average_positions??0).toFixed(2),`${s.active_days??0} / ${s.trading_days??r.curve.length}`,String(s.days_at_target??0),percent(s.average_exposure_pct??0)].forEach(v=>cadence.append(cells(v)));const cadenceTable=table(['目标持仓数','平均持仓数','有交易的天数','持有4–5只的天数','平均资金使用率'],[cadence]);cadenceTable.classList.add('plan-table','replay-metrics');add(cadenceTable);
 add(n('h2','账户收益曲线'));const svgNS='http://www.w3.org/2000/svg',svg=document.createElementNS(svgNS,'svg');const chartWidth=Math.max(360,Math.min(1000,main.clientWidth-56)),right=chartWidth-20;svg.setAttribute('viewBox',`0 0 ${chartWidth} 270`);svg.setAttribute('role','img');svg.setAttribute('aria-label',`模拟账户收益曲线，期末收益${percent(s.return_pct)}，最大回撤${percent(s.max_drawdown_pct)}`);svg.classList.add('replay-chart');
 const values=r.curve.map(p=>p.return_pct),lo=Math.min(0,...values),hi=Math.max(0,...values),padding=Math.max(.01,(hi-lo)*.2),min=lo-padding,max=hi+padding;
 const x=i=>70+i/(r.curve.length-1)*(right-70),y=v=>225-(v-min)/(max-min)*200;
 const shape=(tag,attrs,text)=>{const e=document.createElementNS(svgNS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text)e.textContent=text;svg.append(e);return e};
 for(let i=0;i<5;i++){const v=min+(max-min)*i/4;shape('line',{x1:70,x2:right,y1:y(v),y2:y(v),stroke:'#dcd6ca','stroke-width':1});shape('text',{x:60,y:y(v)+4,'text-anchor':'end',fill:'#606b7b','font-size':12},v.toFixed(2)+'%')}
 for(const i of (chartWidth<600?[0,r.curve.length-1]:[0,Math.round(r.curve.length/3),Math.round(2*r.curve.length/3),r.curve.length-1]))shape('text',{x:x(i),y:255,'text-anchor':i===0?'start':i===r.curve.length-1?'end':'middle',fill:'#606b7b','font-size':12},r.curve[i].date);
 shape('polyline',{points:r.curve.map((p,i)=>`${x(i)},${y(p.return_pct)}`).join(' '),fill:'none',stroke:'#214d70','stroke-width':2.5});add(svg);
 const last=r.curve.at(-1);add(n('p',`同期价格收益：QQQ ${percent(last.qqq_pct)} · SPY ${percent(last.spy_pct)}。基准按期初全额持有，模拟账户单股最高 ${s.max_position_pct ?? 3}%，同时受风险预算约束。`,'note'));
 add(n('h2','完整交易记录'));add(table(['股票','买入日期 / 均价','卖出日期 / 均价','数量','净收益金额','单笔收益率','退出原因'],r.trades.map(t=>{const tr=n('tr');tr.append(stock(t),cells(t.entry_date,money(t.entry_price)),cells(t.exit_date,money(t.exit_price)),cells(t.quantity+'股'),cells(money(t.pnl),null,t.pnl>=0?'gain':'loss'),cells(percent(t.return_pct)),cells(t.reason));return tr})));
 add(n('h2','逐笔模拟成交'));const download=n('a','下载逐笔成交 CSV','link-button');download.href=abc?'replay-abc-fills.csv':'replay-fills.csv';download.download='美股模拟成交.csv';add(download);add(table(['日期','股票','方向','成交价','股数','费用','触发依据'],r.fills.map(t=>{const tr=n('tr');tr.append(cells(t.date),stock(t),cells(t.side),cells(money(t.price)),cells(String(t.quantity)),cells(money(t.commission)),cells(t.reason,'信号日 '+t.signal_date));return tr})));
 if(r.holdings.length){add(n('h2','期末模拟持仓'));add(table(['股票','股数','买入均价','期末收盘','持仓市值','浮动盈亏'],r.holdings.map(t=>{const tr=n('tr');tr.append(stock(t),cells(String(t.quantity)),cells(money(t.entry_price)),cells(money(t.close)),cells(money(t.market_value)),cells(money(t.unrealized_pnl)));return tr})));}
 if(r.skipped?.length){add(n('h2','未成交的信号'));add(table(['股票','信号日','次日开盘','取消原因'],r.skipped.map(t=>{const tr=n('tr');tr.append(stock(t),cells(t.signal_date),cells(money(t.open)),cells(t.reason));return tr})));}
 if(r.pending_signals?.length)add(n('p',r.end+' 收盘后仍有 '+r.pending_signals.length+' 个信号；下一交易日超出本次回放区间，未计模拟成交。','note'));
 const details=n('details',null,'scenario');details.append(n('summary','回放口径与限制'));r.assumptions.forEach(t=>details.append(n('p',t,'note')));add(details);
}

function recommendations(){
 heading('推荐名单','美股 · A股');
 const u=data.u;
 if(u?.trading_system?.plans){
  const t=u.tonight,live=new Map(t.candidates.map(r=>[r.code,r]));
  add(n('h2','美股'),n('p',`完整日线 ${t.daily_as_of} RTH · 计划 ${date(t.generated_at_bj)} 北京 · USD`,'meta'));
  const entries=Object.entries(u.trading_system.plans).sort(([a],[b])=>Number(live.has(b))-Number(live.has(a)));
  add(table(['股票','优先级 / 状态','买入确认','止损','减仓 / 卖出目标','目标收益率'],entries.map(([code,p])=>{
   const r=live.get(code),entry=r?.buy_confirmation??p.entry.confirmation_price,stop=r?.invalidation??p.exit.invalidation_price,reduce=r?.first_reduce??p.exit.reduce_price,target=r?.final_target??p.exit.final_target_price;
   const tr=n('tr');tr.append(stock({name:p.name,code}),cells(r?'今晚优先':'计划候选',t.market_gate_closed?'市场门关闭 · 只观察':r?.action||p.status),cells(money(entry),r?'最高接受 '+money(r.maximum_acceptable):null),cells(money(stop)),cells(money(reduce)+' / '+money(target)),cells(percent(ret(entry,target,0)),'按确认价至最终目标，未扣费用'));return tr;
  })));
  const link=n('a','查看美股完整交易计划','link-button');link.href='#us/tonight';add(link);
 }else add(n('p','美股推荐数据未读取','empty'));
 const a=data.a?.a;
 if(a){
  const rows=a.rows.filter(r=>r.in_futu);
  add(n('h2','A股'),n('p',`${a.date} 收盘 · 已同步优选 ${rows.length} 只 · CNY`,'meta'));
  add(table(['股票','收盘价','当前阶段','结构 / 形态'],rows.map(r=>{const tr=n('tr');tr.append(stock(r),cells(money(r.close)),cells(r.stage),cells(r.shape));return tr})));
  const link=n('a','查看 A股候选与条件','link-button');link.href='#a/observe';add(link);
 }else add(n('p','A股推荐数据未读取','empty'));
}

function refreshPage(){heading('刷新记录',data.sync.checked_at);const rows=data.sync.modules.map(r=>{const tr=n('tr');[r.name,r.source_date,r.checked_at,r.status].forEach(v=>tr.append(cells(v)));return tr});add(table(['模块','源内容时间','检查时间','结果'],rows));add(n('h2','定时任务'));add(table(['任务','频率','状态','归属'],data.schedule.jobs.map(r=>{const tr=n('tr');[r.name,r.cadence,r.status,r.owner].forEach(v=>tr.append(cells(v)));return tr})));}
function render(){if(!loaded)return;let route=location.hash.slice(1);if(!route||route==='home'){route='recommendations';history.replaceState(null,'','#'+route)}let [market,view]=route.split('/');main.replaceChildren();$('#sections').replaceChildren();document.querySelectorAll('.topbar nav a').forEach(a=>{const on=a.dataset.market?a.dataset.market===market:a.hash==='#'+market;if(on)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(views[market])for(const [id,title] of views[market]){const a=n('a',title);a.href=`#${market}/${id}`;if(id===view)a.setAttribute('aria-current','page');$('#sections').append(a)}try{if(market==='recommendations')recommendations();else if(market==='refresh')refreshPage();else if(view==='pre'||view==='post'&&market==='a')report(market,view);else if(['replay','replay-abc'].includes(view)&&market==='us')replayPage();else if(view==='midterm')aPlans();else if(view==='tonight'||view==='post')usPlans();else if(['observe','mobserve'].includes(view))candidates(market);else if(view==='cl20')signals(market);else if(view==='rules')rules(market);else if(view==='original'){heading('中线规划原文',data.mid.as_of.slice(0,10));add(markdown(data.mid.original));}else if(view==='structure'){heading('美股半小时结构',date(data.u.structure.asof,'America/New_York')+' ET');if(!data.u.structure.ready)add(n('p',data.u.structure.status,'state'));else add(table(['股票','变化','板块'],data.u.structure.rows.map(r=>{const tr=n('tr');tr.append(stock(r),cells(r.change),cells(r.board_name));return tr})));}else{history.replaceState(null,'','#us/tonight');render();return}}catch(e){add(n('p','这个栏目读取失败，请点击“重新读取”。','empty'));console.error(e)}}
async function refresh(manual=false){$('#reload').disabled=true;const results=await Promise.allSettled(Object.entries(paths).map(async([key,path])=>{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(key);return [key,await r.json()]}));failures=[];for(let i=0;i<results.length;i++){const r=results[i];if(r.status==='fulfilled')data[r.value[0]]=r.value[1];else failures.push(Object.keys(paths)[i])}const next=JSON.stringify(Object.fromEntries(Object.entries(data).filter(([k])=>k!=='sync')));const changed=signature!==next;signature=next;loaded=true;$('#load-status').textContent=failures.length?'部分来源读取失败，保留已读取内容':'最近读取 '+new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());$('#reload').disabled=false;if(manual||(changed&&!main.contains(document.activeElement)&&!document.querySelector('.detail-row')))render()}
$('#reload').onclick=()=>refresh(true);$('#clock').textContent=today('Asia/Shanghai')+' · 北京';window.addEventListener('hashchange',()=>{lane='all';search='';signalDate='';render();window.scrollTo(0,0)});refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);
